export const transaction_page = {
    new_btn: '[data-test="nav-top-new-transaction"]',
    mine_btn: '[data-test="nav-personal-tab"]',
    search: '#user-list-search-input',
    userList: '[data-test="users-list"]',
    amount_fld: '#amount',
    note_fld: '#transaction-create-description-input',
    amount_error: '#transaction-create-amount-input-helper-text',
    note_error: '#transaction-create-description-input-helper-text',
    pay_btn: '[data-test="transaction-create-submit-payment"]',
    request_btn: '[data-test="transaction-create-submit-request"]',
    transaction_list: '[data-test="transaction-list"]',
    accept_request_btn: '[data-test*="transaction-accept-request"]',
    return_btn: '[data-test="new-transaction-return-to-transactions"]',
    trnsct_popup: '[data-test="alert-bar-success"]',
    balance: '[data-test="sidenav-user-balance"]',
    notification_icon: '[data-test="nav-top-notifications-link"]',
    like_btn: '[data-test*="transaction-like-button"]',
    notifications_list: '[data-test*="notification-list"]',
    trnsct_comment_input: '[data-test*="transaction-comment-input"]',
    trnsct_view_tabs: '[data-test="nav-transaction-tabs"]',
    like_count: '[data-test*="transaction-like-count"]',
    comment_list: '[data-test*="comment-list"]',
    rjct_rqst: '[data-test*="transaction-reject-request"]'
}